# C3 - Cluster Command & Control Suite
# Oak Ridge National Laboratory, Oak Ridge, TN,
# Authors:  Geoffroy Vallee
# (C) 2007 All Rights Reserved

PREFIX=
MANDIR=$(PREFIX)

all:

install:
	install -d $(MANDIR)
	install -d $(MANDIR)/man1
	install -d $(MANDIR)/man4
	install -d $(MANDIR)/man5
	install -m 644 man1/* $(MANDIR)/man1
	install -m 644 man4/* $(MANDIR)/man4
	install -m 644 man5/* $(MANDIR)/man5
